### ISSUE TITLE
Do not work...

### ISSUE THREAD

**Issue by aborriginal** [games647/BitcoinQRCode#1]
Hello! Uploaded to my domain in subfolder /qr - nothing happens...
What can be the problem? Thanks!

**Comment by TuxCoding** [comment]
Do you have JavaScript disabled? Could you try to open the Browser developer window (F12 on most browser) and then take a look for any errors on the network or console tab after refreshing the page.

**Comment by aborriginal** [comment]
Yes, JS enabled.
Errors:
Failed to load resource: net::ERR_CONNECTION_REFUSED
2jquery.qrcode.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
2bitcoinqrcode.js:167 Uncaught TypeError: $(...).qrcode is not a function
    at App.draw (bitcoinqrcode.js:167)
    at App.update (bitcoinqrcode.js:136)

**Comment by TuxCoding** [comment]
You forgot to include the git submodule. 
If you download it using `git`, you have to initialize the submodule. If you downloaded using a ZIP archive, you can download it manually. Go to the lib folder and click on the jquery-qrcode link. This redirects to the corresponding version of the submodule project. There you need to download it and include it in the lib folder of this project.

**Comment by aborriginal** [comment]
Do not understand, sorry. I want use this on domain, look here, f.e. http://satno.com/qr
I thought I just need to upload folder there and open page...

**Comment by TuxCoding** [comment]
Yes, but this project includes a library dependency on another project. Instead of copying the raw files, this projects sets a version number of this dependency for easier updating to a new version.

Download the dependency from here: https://github.com/jeromeetienne/jquery-qrcode/tree/bf626b5064255495812944e3d848b1cdfc2e3e9a

and put the contents into this folder `qr/lib/jquery-qrcode` (qr is from your domain folder)

**Comment by aborriginal** [comment]
Worked like a charm! Thank you!)
